
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = "\x1a\\\xf0\xecm\xcc\xde\x97'\xf8>\x1bg\xc7`o"
    
_lr_action_items = {'BOLD':([7,10,11,13,17,19,20,21,26,27,28,30,31,32,],[9,9,-11,9,9,27,9,-12,9,-14,-13,-15,-8,-7,]),'BULLET':([7,10,11,13,17,20,21,26,27,28,30,31,32,],[10,10,-11,10,10,10,-12,10,-14,-13,-15,-8,-7,]),'PLAINTEXT':([7,9,10,11,12,13,15,16,17,20,21,26,27,28,30,31,32,],[11,19,11,-11,22,11,24,25,11,11,-12,11,-14,-13,-15,-8,-7,]),'DOUBLEHASH':([7,11,13,17,21,22,26,27,28,30,31,32,],[12,-11,12,-9,-12,29,-10,-14,-13,-15,-8,-7,]),'NEWLINE':([0,2,3,4,5,7,8,11,13,14,17,20,21,23,25,26,27,28,29,30,31,32,],[3,5,3,7,8,-6,3,21,-6,-4,-9,28,-12,-5,31,-10,-14,-13,32,-15,-8,-7,]),'ENVIRON':([0,3,8,],[4,4,4,]),'ITALIC':([7,10,11,13,17,20,21,24,26,27,28,30,31,32,],[15,15,-11,15,15,15,-12,30,15,-14,-13,-15,-8,-7,]),'ATTRIBUTE':([7,11,13,17,21,26,27,28,30,31,32,],[16,-11,16,-9,-12,-10,-14,-13,-15,-8,-7,]),'$end':([0,1,3,6,8,18,],[-3,0,-3,-2,-3,-1,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'content':([7,13,],[14,23,]),'md':([0,3,8,],[1,6,18,]),'slide':([0,3,8,],[2,2,2,]),'elem':([7,13,],[13,13,]),'text':([7,10,13,17,20,26,],[17,20,17,26,26,26,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> md","S'",1,None,None,None),
  ('md -> slide NEWLINE NEWLINE md','md',4,'p_md','parser.py',17),
  ('md -> NEWLINE md','md',2,'p_md_newline','parser.py',22),
  ('md -> <empty>','md',0,'p_md_empty','parser.py',27),
  ('slide -> ENVIRON NEWLINE content','slide',3,'p_slide','parser.py',32),
  ('content -> elem content','content',2,'p_content','parser.py',37),
  ('content -> <empty>','content',0,'p_content_empty','parser.py',42),
  ('elem -> DOUBLEHASH PLAINTEXT DOUBLEHASH NEWLINE','elem',4,'p_elem_title','parser.py',47),
  ('elem -> ATTRIBUTE PLAINTEXT NEWLINE','elem',3,'p_elem_atrribute','parser.py',52),
  ('elem -> text','elem',1,'p_elem_text','parser.py',57),
  ('text -> text text','text',2,'p_text','parser.py',62),
  ('text -> PLAINTEXT','text',1,'p_text_plain','parser.py',67),
  ('text -> PLAINTEXT NEWLINE','text',2,'p_text_plainnewline','parser.py',72),
  ('text -> BULLET text NEWLINE','text',3,'p_text_bullet','parser.py',82),
  ('text -> BOLD PLAINTEXT BOLD','text',3,'p_bold','parser.py',88),
  ('text -> ITALIC PLAINTEXT ITALIC','text',3,'p_italic','parser.py',92),
]
